-- Adding Company customization parameters
------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'CompanyName')
	ALTER TABLE dbo.[GlobalSettings] ADD [CompanyName] VARCHAR(500) DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'CompanyAddress')
	ALTER TABLE dbo.[GlobalSettings] ADD [CompanyAddress] VARCHAR(2000) DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'AccountName')
	ALTER TABLE dbo.[GlobalSettings] ADD [AccountName] VARCHAR(200) DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'AccountNumber')
	ALTER TABLE dbo.[GlobalSettings] ADD [AccountNumber] VARCHAR(20) DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'SortCode')
	ALTER TABLE dbo.[GlobalSettings] ADD [SortCode] VARCHAR(20) DEFAULT('')

-- Adding Phone for Customer
------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CUSTOMER' AND [COLUMN_NAME] = 'Phone')
	ALTER TABLE dbo.[CUSTOMER] ADD [Phone] VARCHAR(100) NOT NULL DEFAULT('')

-- Adding Table for Credit Note
------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_NAME] = 'CreditNote' AND [TABLE_TYPE] = 'BASE TABLE')
	CREATE TABLE dbo.[CreditNote]
			([ID]					INT				NOT NULL IDENTITY(1,1)
			,[ClientId]				INT				NOT NULL
			,[TransactionNumber]	VARCHAR(50)		NOT NULL DEFAULT('')
			,[TransactionDate]		DATETIME		NOT NULL DEFAULT(GETDATE())
			,[Description]			VARCHAR(500)	NOT NULL DEFAULT('')
			,[Amount]				MONEY			NOT NULL DEFAULT(0))

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE [TABLE_NAME] = 'CreditNote' AND [CONSTRAINT_TYPE] = 'PRIMARY KEY')
	ALTER TABLE dbo.[CreditNote] ADD CONSTRAINT PK_CreditNote PRIMARY KEY(ID)

-- Adding table for Company (Multi-Company)
-------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_NAME] = 'Company' AND [TABLE_TYPE] = 'BASE TABLE')
	CREATE TABLE dbo.[Company]
			([ID]		INT NOT NULL IDENTITY(1,1)
			,[Name]		VARCHAR(100) NOT NULL
			,[Code]		VARCHAR(50)  NULL
			,[Address]	VARCHAR(500) NULL
			,[City]		VARCHAR(100) NULL
			,[State]	VARCHAR(100) NULL
			,[Country]	VARCHAR(100) NULL
			,[ZIP]		VARCHAR(10) NULL
			,[Phone]	VARCHAR(100) NULL
			,[Fax]		VARCHAR(100) NULL
			,[Email]	VARCHAR(100) NULL
			,[URL]		VARCHAR(100) NULL)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE [TABLE_NAME] = 'Company' AND [CONSTRAINT_TYPE] = 'PRIMARY KEY')
	ALTER TABLE dbo.[Company] ADD CONSTRAINT PK_Company PRIMARY KEY(ID)

-- Adding table for Users (Multi-Company)
-------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_NAME] = 'Users' AND [TABLE_TYPE] = 'BASE TABLE')
	CREATE TABLE dbo.[Users]
			([ID]		INT NOT NULL IDENTITY(1,1)
			,[Name]		VARCHAR(50) NOT NULL 
			,[Password] VARCHAR(50) NOT NULL
			,[IsActive]	BIT NOT NULL DEFAULT(1))

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE [TABLE_NAME] = 'Users' AND [CONSTRAINT_TYPE] = 'PRIMARY KEY')
	ALTER TABLE dbo.[Users] ADD CONSTRAINT PK_Users PRIMARY KEY(ID)

-- Adding table for Company-User mapping (Multi-Company)
--------------------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE [TABLE_NAME] = 'CompanyUsers' AND [TABLE_TYPE] = 'BASE TABLE')
	CREATE TABLE dbo.[CompanyUsers]
			([ID]			INT NOT NULL IDENTITY(1,1)
			,[UserId]		INT
			,[CompanyId]	INT)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE [TABLE_NAME] = 'CompanyUsers' AND [CONSTRAINT_TYPE] = 'PRIMARY KEY')
	ALTER TABLE dbo.[CompanyUsers] ADD CONSTRAINT PK_CompanyUsers PRIMARY KEY(ID)

-- Adding CompanyId In tables (Multi-Company)
---------------------------------------------
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Customer' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[Customer] ADD [CompanyId] INT NOT NULL DEFAULT(0)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Client' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[Client] ADD [CompanyId] INT NOT NULL DEFAULT(0)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'ChargeHead' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[ChargeHead] ADD [CompanyId] INT NOT NULL DEFAULT(0)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[CreditNote] ADD [CompanyId] INT NOT NULL DEFAULT(0)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'BreakDown' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[BreakDown] ADD [CompanyId] INT NOT NULL DEFAULT(0)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[Invoice] ADD [CompanyId] INT NOT NULL DEFAULT(0)

-- Customization in Company and GlobalSettings table for Invoice Csv generation
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Company' AND [COLUMN_NAME] = 'AccountCode')
	ALTER TABLE dbo.[Company] ADD [AccountCode] VARCHAR(10) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Company' AND [COLUMN_NAME] = 'AccountNumber')
	ALTER TABLE dbo.[Company] ADD [AccountNumber] VARCHAR(10) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'SmtpFromAddress')
	ALTER TABLE dbo.[GlobalSettings] ADD [SmtpFromAddress] VARCHAR(100) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'SmtpUser')
	ALTER TABLE dbo.[GlobalSettings] ADD [SmtpUser] VARCHAR(100) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'SmtpPassword')
	ALTER TABLE dbo.[GlobalSettings] ADD [SmtpPassword] VARCHAR(100) NOT NULL DEFAULT('')

-- Adding narration column for Invoice and Credit Note to be printed in CSV export
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'Narration')
	ALTER TABLE dbo.[Invoice] ADD [Narration] VARCHAR(500) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'Narration')
	ALTER TABLE dbo.[CreditNote] ADD [Narration] VARCHAR(500) NOT NULL DEFAULT('')

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'StartDate')
	ALTER TABLE dbo.[Invoice] ADD [StartDate] DATETIME NULL

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'EndDate')
	ALTER TABLE dbo.[Invoice] ADD [EndDate] DATETIME NULL

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'Printed')
	ALTER TABLE dbo.[Invoice] ADD [Printed] BIT NOT NULL DEFAULT(0)

-- Deleted flag added in Invoice and CreditNote
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'Deleted')
	ALTER TABLE dbo.[Invoice] ADD [Deleted] BIT NULL DEFAULT(0) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'Deleted')
	ALTER TABLE dbo.[CreditNote] ADD [Deleted] BIT NULL DEFAULT(0) WITH VALUES

-- Adding CustomerId and Posted flag in Credit Note
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'CustomerId')
	ALTER TABLE dbo.[CreditNote] ADD [CustomerId] INT NULL
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'Printed')
	ALTER TABLE dbo.[CreditNote] ADD [Printed] BIT NULL DEFAULT(0) WITH VALUES

-- Making Settings customization on per-Company basis
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'GlobalSettings' AND [COLUMN_NAME] = 'CompanyId')
	ALTER TABLE dbo.[GlobalSettings] ADD [CompanyId] INT NULL DEFAULT(0) WITH VALUES

-- Adding Narrative column in Client table
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Client' AND [COLUMN_NAME] = 'Narrative')
	ALTER TABLE dbo.[Client] ADD [Narrative] VARCHAR(500) NOT NULL  DEFAULT('') WITH VALUES

-- Adding User printed option
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Invoice' AND [COLUMN_NAME] = 'UserPrinted')
	ALTER TABLE dbo.[Invoice] ADD [UserPrinted] bit NULL DEFAULT(0)	WITH VALUES
	
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CreditNote' AND [COLUMN_NAME] = 'UserPrinted')
	ALTER TABLE dbo.[CreditNote] ADD [UserPrinted] bit NULL DEFAULT(0)	WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Client' AND [COLUMN_NAME] = 'IsDeleted')
	ALTER TABLE dbo.[Client] ADD [IsDeleted] BIT NULL DEFAULT(0) WITH VALUES
	
IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Customer' AND [COLUMN_NAME] = 'IsDeleted')
	ALTER TABLE dbo.[Customer] ADD [IsDeleted] BIT NULL DEFAULT(0) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Customer' AND [COLUMN_NAME] = 'PhysicalPrintRequired')
	ALTER TABLE dbo.[Customer] ADD [PhysicalPrintRequired] BIT NULL DEFAULT(1) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'BreakdownDetail' AND [COLUMN_NAME] = 'IsActive')
	ALTER TABLE dbo.[BreakdownDetail] ADD [IsActive] BIT NULL DEFAULT(1) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'BreakdownDetail' AND [COLUMN_NAME] = 'InvoiceCycle')
	ALTER TABLE dbo.[BreakdownDetail] ADD [InvoiceCycle] TINYINT NULL DEFAULT(1) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Invoice' AND COLUMN_NAME = 'MultiMonth')
	ALTER TABLE dbo.[Invoice] ADD [MultiMonth] BIT DEFAULT(0) WITH VALUES

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Client' AND COLUMN_NAME = 'Rip')
	ALTER TABLE dbo.[Client] ADD [Rip] DATETIME NULL

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GlobalSettings' AND COLUMN_NAME = 'LetterContent')
	ALTER TABLE dbo.GlobalSettings ADD [LetterContent] VARCHAR(MAX)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'AmalgamatedInvoice')
	CREATE TABLE dbo.[AmalgamatedInvoice]
		([ID]				INT NOT NULL IDENTITY(1,1),
		 [InvoiceNumber]	VARCHAR(50) NOT NULL,
		 [InvoiceDate]		DATETIME NOT NULL,
		 [CustomerId]		INT NOT NULL,
		 [NetAmount]		MONEY NOT NULL DEFAULT(0),
		 [CompanyId]		INT NOT NULL,
		 [Narration]		VARCHAR(500) NULL,
		 [StartDate]		DATETIME NOT NULL,
		 [EndDate]			DATETIME NOT NULL,
		 [Printed]			BIT	NOT NULL DEFAULT(0),
		 [Deleted]			BIT NULL,
		 [UserPrinted]		BIT NULL,
		 [MultiMonth]		BIT NULL)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND CONSTRAINT_NAME = 'PK_AmalgamatedInvoice')
	ALTER TABLE dbo.[AmalgamatedInvoice] ADD CONSTRAINT PK_AmalgamatedInvoice PRIMARY KEY(ID)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'AmalgamatedInvoiceDetail')
	CREATE TABLE dbo.[AmalgamatedInvoiceDetail]
		([ID]					INT NOT NULL IDENTITY(1,1),
		 [AmalgamatedInvoiceId]	INT NOT NULL,
		 [ClientId]				INT NOT NULL,
		 [ChargeHeadId]			INT NOT NULL,
		 [WeeklyRate]			MONEY NOT NULL DEFAULT(0),
		 [Days]					INT NOT NULL DEFAULT(0),
		 [SubTotal]				MONEY NOT NULL DEFAULT(0),
		 [ExtraHead]			VARCHAR(50),
		 [ExtraAmount]			MONEY NOT NULL DEFAULT(0),
		 [LessHead]				VARCHAR(50),
		 [LessAmount]			MONEY NOT NULL DEFAULT(0),
		 [TotalAmount]			MONEY NOT NULL DEFAULT(0)
		)

IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND CONSTRAINT_NAME = 'PK_AmalgamatedInvoiceDetail')
	ALTER TABLE dbo.[AmalgamatedInvoiceDetail] ADD CONSTRAINT PK_AmalgamatedInvoiceDetail PRIMARY KEY(ID)