//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInvoice.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerInvoice.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Adding Company customization parameters
        ///------------------------------------------
        ///IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = &apos;GlobalSettings&apos; AND [COLUMN_NAME] = &apos;CompanyName&apos;)
        ///	ALTER TABLE dbo.[GlobalSettings] ADD [CompanyName] VARCHAR(500) DEFAULT(&apos;&apos;)
        ///
        ///IF NOT EXISTS(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = &apos;GlobalSettings&apos; AND [COLUMN_NAME] = &apos;CompanyAddress&apos;)
        ///	ALTER TABLE dbo.[GlobalSettings] ADD [CompanyAddress] VARCHAR(2000) DEFAULT( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlterTable {
            get {
                return ResourceManager.GetString("AlterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM InvoiceDetail WHERE InvoiceId&gt;@InvoiceNumber
        ///DELETE FROM Invoice WHERE Id&gt;@InvoiceNumber
        ///
        ///DBCC CHECKIDENT(&apos;Invoice&apos;, RESEED, @InvoiceNumber).
        /// </summary>
        internal static string ResetInvoiceScript {
            get {
                return ResourceManager.GetString("ResetInvoiceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author	  :	&lt;Debasis C.&gt;
        ///-- Create date: &lt;01-Nov-2019&gt;
        ///-- Description:	&lt;Checks whether to generate invoice for a customer if any of the client(s) are marked RIP&gt;
        ///-- Usage	  : exec usp_CheckClientRip 1, &apos;30-Oct-2019&apos;
        ///-- =============================================
        ///CREATE PROCEDURE usp_CheckClientRip
        ///	@CompanyId	INT,
        ///	@InvoiceEndDate	DATETIME
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///	SELECT
        ///		 C.Id
        ///	FROM dbo.BreakDown B WITH(NOLOCK)
        ///	JOIN dbo.BreakDownDeta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usp_CheckClientRip {
            get {
                return ResourceManager.GetString("usp_CheckClientRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE usp_Invoice_History
        ///	@CompanyId	INT
        ///AS
        ///BEGIN
        ///	CREATE TABLE #InvoiceHistory
        ///		(
        ///			[Select]		BIT,
        ///			[Id]			BIGINT,
        ///			[InvoiceNumber]	VARCHAR(50),
        ///			[InvoiceDate]	DATETIME,
        ///			[ClientCode]	VARCHAR(50),
        ///			[ClientName]	VARCHAR(100),
        ///			[CustomerCode]	VARCHAR(50),
        ///			[CustomerName]	VARCHAR(100),
        ///			[ChargeName]	VARCHAR(100),
        ///			[WeeklyRate]	MONEY,
        ///			[Days]			INT,
        ///			[SubTotal]		MONEY,
        ///			[ExtraHead]		VARCHAR(100),
        ///			[ExtraAmount]	MONEY,
        ///			[LessHead]		VARCHAR(100),
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usp_Invoice_History {
            get {
                return ResourceManager.GetString("usp_Invoice_History", resourceCulture);
            }
        }
    }
}
